XIAO-109: [Auth Server] Apply user details manager with my sql db
nvthiet1995/xiao-authserver pull request #3
Opened 2024-04-03 04:08 UTC by tnd-dev99

Create:
- User entity
- User repo
- Xiao user detail

2024-04-03 04:48 UTC, mtienit93 requested changes

2024-04-03 04:48 UTC, mtienit93 commented on pom.xml
> +		<dependency>
please refer how to add lombok dependency in xiao-users (pom.xml in xiao-users)

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetailsService.java
> +    @Override
break line please

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetails.java
> +public class XiaoUserDetails implements UserDetails {
why do we need this class?

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetailsService.java
> +        if(user != null){
Why do not use Java 8 here? I put this comment many times before?

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetailsService.java
> +        throw new UsernameNotFoundException("Could not find user with email: "+ email);
use String.format instead of plus string

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/repository/UserRepository.java
> +    User getUserByEmailAddress(String email);
use findByEmailAddress

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/entity/User.java
> +    @Column(nullable = false, length = 100)
why don't we have the column name here?

2024-04-03 04:48 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/entity/User.java
> +@Builder
Do we need @Builder, @ToString, @Getter, @Setter..v.v ?

2024-04-04 06:14 UTC, nvthiet1995 commented on src/main/resources/db/migration/V0_0_1_20240403234030__create-users-table.sql
> +    `created_at` date NOT NULL,
where are these fields used?

2024-04-04 07:10 UTC, nvthiet1995 commented on src/main/resources/db/migration/V0_0_1_20240403234120__insert-an-user-into-users-table.sql
> +    'danh',
Please update this user information to something general like 'admin/password' and add it to the README file as well.

2024-04-04 07:12 UTC, nvthiet1995 commented on src/main/resources/db/migration/V0_0_1_20240329124018__insert-oidc-registered-client.sql
>  VALUES('1d0ae4d0-0ec5-4f64-92aa-db46d718ebae', 'oidc-client', '2024-03-28 15:20:33',
Please help me to add this credentail information to README file as well:
Default registered client infor:
- client_id: oidc-client
- client_secret: secret

2024-04-04 09:03 UTC, mtienit93 requested changes

2024-04-04 09:03 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetailsService.java
> +    @Autowired
our project doesn't use @AutoWired

2024-04-04 09:03 UTC, mtienit93 commented on src/main/java/com/xiao/authserver/security/XiaoUserDetailsService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
Do we need throws UsernameNotFoundException?

2024-04-05 15:41 UTC, mtienit93 approved these changes
LGTM!

2024-04-05 15:43 UTC, merged